services:
  - type: web
    name: aura-os-jarvis
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start_server.sh
    plan: free
    region: singapore
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ENVIRONMENT
        value: production
      - key: APP_NAME
        value: AURA-OS | Autonomous JARVIS Hub
      - key: RUN_TELEGRAM_BOT
        value: "true"
      - key: TELEGRAM_AUTHORIZED_USER_ID
        value: "6233907249"
      - key: CORS_ORIGINS
        value: '["*"]'
      - key: HOST
        value: 0.0.0.0
      - key: PC_BRIDGE_SECRET
        value: mukil-aura-pc-bridge-secret-2026
      - key: DRIVE_FOLDER_ID
        value: 1iaHzDzC7KiJk2FlMdS7eNW7vkYxDeaXZ
      - key: DRIVE_MAIN_BILLS_FOLDER_ID
        value: 11KMBP0HHa2AFl30zjL8-a_-BQk9MgWM9
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
